### ISSUE TITLE
CRC Cards & Class Diagrams

### ISSUE THREAD

**Issue by ls3233** [gabriellet/thepriceisright#1]
[ExceptionHandlers_TeamAssignment2.pdf](https://github.com/gabriellet/thepriceisright/files/540651/ExceptionHandlers_TeamAssignment2.pdf)

**Comment by gabriellet** [comment]
Moved to wiki

**Comment by gabriellet** [comment]
Contains CRC Cards, Class diagrams described. (UML Diagrams added later).
To Do:
- [x] Implement SQLite database to match UML diagram.
- [x] Ensure application structure matches CRC cards. Keep responsibilities delegated in correct classes.
