### ISSUE TITLE
Use AJAX for dynamic UI display

### ISSUE THREAD

**Issue by ls3233** [gabriellet/thepriceisright#11]
Its troublesome for customers to continually refresh their homepage to see how their order is progressing. Use AJAX to dynamically display update in order progress.

**Comment by gabriellet** [comment]
Possibly useful information [here](https://zinoui.com/blog/ajax-request-progress-bar)

**Comment by gabriellet** [comment]
More possibly useful [~information~](http://www.w3schools.com/jquery/jquery_ajax_intro.asp)

**Comment by gabriellet** [comment]
[MOAR INFOS HERE](http://www.w3schools.com/jquery/jquery_ref_ajax.asp)

**Comment by gabriellet** [comment]
Older but possibly [still relevant](http://stackoverflow.com/questions/6835835/jquery-simple-polling-example)

**Comment by gabriellet** [comment]
More actually useful things:
- [Ruby Example](http://www.thegreatcodeadventure.com/polling-with-javascript-jquery/)
- [StackOverflow](http://stackoverflow.com/questions/6835835/jquery-simple-polling-example?noredirect=1&lq=1)
- [StackOverflow](http://stackoverflow.com/questions/16522578/periodically-fetch-data-and-display-it-with-django?noredirect=1&lq=1)
- [This Blog](https://techoctave.com/c7/posts/60-simple-long-polling-example-with-javascript-and-jquery)

_dies from too many web pages_

**Comment by fennilin** [comment]
or simple javascript refresh, with timer (3, 2, 1, refresh, etc.)

**Comment by gabriellet** [comment]
Fixed 1188fa1

**Comment by gabriellet** [comment]
Also 8a76ddd
