### ISSUE TITLE
Requirements and Wireframes

### ISSUE THREAD

**Issue by Aaronong** [gabriellet/thepriceisright#2]
Link to document https://docs.google.com/document/d/19mXeAbC19ev0KygBCEGzsHfcyNEqz9NauavQ9l2xtHs/edit?ts=5808163f

**Comment by gabriellet** [comment]
Moved to wiki

**Comment by gabriellet** [comment]
Contains use cases and wireframes. To do:
- [x] implement "Use case 1:  Place Order" 
- [x] implement "Use case 2: Monitor Order"
- [x] implement UI as per wireframes

See Trello task board for details.
