### ISSUE TITLE
Graceful error handling for when a ParentOrder fails

### ISSUE THREAD

**Issue by ls3233** [gabriellet/thepriceisright#5]
Right now when a ParentOrder fails to complete (e.g. rejected by market simulator), it does not send any error message. Instead, the progress bar still displays as "30%" complete, which is extremely misleading for users. Notify our users immediately when their order fails.

**Comment by gabriellet** [comment]
I think this lives in both front and back end right? Did Lin want a pop up immediately when it failed? Or highlight that order red? @ls3233 @Aaronong what exactly did he say he wanted?

**Comment by gabriellet** [comment]
Todo: 
- [x] Add error field to database
- [x] On error, mark true
- [x] Put trades with error in separate list from in progress and completed

**Comment by gabriellet** [comment]
Fixed in commit 486295b, 88c94a2
