### ISSUE TITLE
Fix progress bar bug when viewing individual parent/child orders

### ISSUE THREAD

**Issue by ls3233** [gabriellet/thepriceisright#8]
Clicking on a Parent order to view all its child orders presents a faulty progress bar (stays at 0% then suddenly jumps to 100% on completion). 
This is misleading especially because on our index page, we display the actually progress correctly

**Comment by gabriellet** [comment]
@ls3233 You said you'd submitted this, right?

**Comment by ls3233** [comment]
@gabriellet No this is a different issue. What I DID fix is that if a ParentOrder fails, it now updates its status to status=FAILED. However there is no UI display for this.

What this issue is talking about is if you click a ParentOrder in the midst of trading to look at all its ChildOrders. The progress bar will display as 0% throughout the trade, and jump to 100% when the entire trade is done

**Comment by gabriellet** [comment]
Fixed by commit a2f1b6e
